### ISSUE TITLE
ObjectMapper serialisation error for LocalDateTime

### ISSUE THREAD

**Issue by hamid646m** [awslabs/aws-lambda-powertools-java#1134] opened 2023-04-17 11:58 UTC
ObjectMapper is not able to serialise `LocalDateTime` and throws:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default
``` 

**What were you trying to accomplish?**

## Expected Behavior
able to serialise `LocalDateTime`

## Current Behavior
exception is thrown

## Possible Solution
running `findAndRegisterModules`

## Steps to Reproduce (for bugs)

1. have a Idempotent method that returns an object with a field of `LocalDateTime`

## Environment

* **Powertools version used**: 1.5.0
* **Packaging format (Layers, Maven/Gradle)**: Maven

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

**Comment by jeromevdl** [comment] 2023-06-05 08:18
Won't fix, see https://github.com/awslabs/aws-lambda-powertools-java/pull/1135#issuecomment-1542115077

Use: `JsonConfig.get().getObjectMapper().registerModule(new JodaModule());`

**Closed by jeromevdl** 2023-06-05 08:18 UTC
Labels: bug, triage

**Comment by mrjv** [comment] 2023-12-09 06:57
@jeromevdl 
The suggested workaround above becomes more complicated in a multi-threaded environment. Especially when the thread is created by an external framework such as Spring Cloud Function. Any particular reason why the ObjectMapper in JsonConfig is wrapped in a ThreadLocal? I believe the ObjectMapper is supposed to be thread safe after it has been configured?

I'm interested in using the idempotency library with a customized ObjectMapper, but without configuring the ObjectMapper every time a new thread is created. Either being able to set the initial value provider of the ThreadLocal<ObjectMapper> or removing the ThreadLocal would solve this use case.

**Comment by jeromevdl** [comment] 2023-12-10 16:38
Thanks for the feedback. You are right `ObjectMapper` is thread safe and we could initialize it as static, but changing its configuration is not thread safe after. @scottgerring , we should discuss this quickly this week

**Comment by mrjv** [comment] 2024-03-19 05:55
@jeromevdl @scottgerring 
Did you have time to discuss this? Any updates?

**Comment by jeromevdl** [comment] 2024-03-19 07:13
Unfortunately, not that much. This is a topic we have in mind and would need to change. The issue is that ObjectMapper cannot be safely modified once configured. Maybe what we should do is the ability to provide your own ObjectMapper, just like we do with the SDK clients. @scottgerring WDYT?
